version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    container_name: sqlserver_with_data
    environment:
      MSSQL_SA_PASSWORD: "Root_123456"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - backend

  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      DB_DRIVER: "ODBC Driver 18 for SQL Server"
      DB_SERVER: db
      DB_PORT: 1433
      DB_USERNAME: sa
      DB_PASSWORD: Root_123456
      DB_NAME: DB
    depends_on:
      - db
    networks:
      - backend

networks:
  backend: